### ISSUE TITLE
It appears the pull requests are not supported.

### ISSUE THREAD

**Issue by stewartbryson** [elgohr/Publish-Docker-Github-Action#10]
On a `['pull_request']` I'm getting the error below. It seems unable to parse the `GITHUB_REF` when using a PR:

```
/usr/bin/docker run --name fe0f2e0b588d71064725882a35d5fbca6f22_6505a8 --label 29fe0f --workdir /github/workspace --rm -e INPUT_NAME -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_SNAPSHOT -e INPUT_DOCKERFILE -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/docker-gradle/docker-gradle":"/github/workspace" 29fe0f:2e0b588d71064725882a35d5fbca6f22

WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

invalid argument "redpillanalytics/docker-gradle:refs/pull/1/merge" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
invalid reference format
An image does not exist locally with the tag: redpillanalytics/docker-gradle
The push refers to repository [docker.io/redpillanalytics/docker-gradle]
Removing login credentials for https://index.docker.io/v1/

```

**Comment by elgohr** [comment]
Why would you want to publish an image of a pull request to a registry?

**Comment by elgohr** [comment]
What would you expect the tag to be?
I'm not sure whether I would really like to support it, as PRs and Branches might collide.

**Comment by stewartbryson** [comment]
> I'm not sure whether I would really like to support it, as PRs and Branches might collide.

So... perhaps you just omit the push when it's a PR? You would still want to do the image build wouldn't you think?

**Comment by elgohr** [comment]
So why not separate them?
See test & publish 
https://github.com/elgohr/concourse-blackduck/tree/master/.github/workflows

**Comment by stewartbryson** [comment]
How do you get the publish to wait until test is successful? If that’s possible, then I think you are right. 

I think at the least it should handle the fact that it’s a PR. Right now it just errors with an obscure error. 

I’ll delete the PR for now and feel free to close this issue. Great action by the way.

**Comment by stewartbryson** [comment]
Also @elgohr... I understand your point about the image name as a secret. I do think that's valuable if you want to accept PRs on this. You might not after the one I opened. ;-)

I'm going ahead with a version that supports PRs, but when a PR, it goes ahead and pushes the snapshot only. I'll also see if I can add the secret stuff. When I'm done, I'll then open the PR... no pressure.

**Comment by elgohr** [comment]
I would like to figure out, how actions handles PRs and secrets. 

If somebody forks a repository and opens a PR, would the secrets of the main or the fork be taken for the job?

If the secrets from the main repository are used, supporting PRs would be a security issue for the person developing the main repository. Somebody would just have to create a PR named "latest" and we would have lot's of fun 😉

**Comment by elgohr** [comment]
As you can see here https://github.com/elgohr/my-secret-action/pull/2 secrets wouldn't be accessible in the Pull request anyway. So this would never work.

**Comment by elgohr** [comment]
Could we close this for now?

**Comment by elgohr** [comment]
Please reopen, if you still see this as an issue.
