### ISSUE TITLE
[BUG] Using a password manager generated password results in an authentication error.

### ISSUE THREAD

**Issue by Nirsiel** [elgohr/Publish-Docker-Github-Action#101]
#### Description:
When using a password generated by password manager (bitwarden), action can't log in to the docker hub.

#### Reproducing
- Use password generated by a password manager, for example, 9eL8*9n92G@!#o^$!&3Nz89F*@%9
- Push and wait to publish action to fail on login

#### Expected behavior
Action should successfully log in to the docker hub and publish an image.

Additional context
When logging to the docker hub through the terminal, I must pass my password as a string ('9eL8*9n92G@!#o^$!&3Nz89F*@%9') for it to use it correctly. I suspect that the offending character is an exclamation mark, but I didn't test every one individually.

**Comment by elgohr** [comment]
Looks like it has to be some other reason, as this passes as expected: https://github.com/elgohr/Publish-Docker-Github-Action/commit/94e33a1557953b353b4392827ccbd6b592245393
