### ISSUE TITLE
Fix published releases on this repo

### ISSUE THREAD

**Issue by artis3n** [elgohr/Publish-Docker-Github-Action#102]
The most recent tag is not the most recent Release for this repo. A little confusing. The Releases should match the latest version on the Actions Marketplace. I would have expected to see 2.21 listed as the latest release.

![image](https://user-images.githubusercontent.com/6969296/92000643-bc6e7480-ed0b-11ea-9978-a980fe15ad48.png)

![image](https://user-images.githubusercontent.com/6969296/92000652-bed0ce80-ed0b-11ea-81f2-7a290da66c19.png)

**Comment by elgohr** [comment]
I guess this is a bug in Github, right?
I mean, I would also expect that, when publishing to the marketplace...

**Comment by artis3n** [comment]
It looks like a bug. The latest release shows up correctly on the Marketplace...
![image](https://user-images.githubusercontent.com/6969296/92394645-e5b64880-f0ef-11ea-9002-9b672032a6ed.png)

**Comment by elgohr** [comment]
Just got demystified. It's the integration test :)
https://github.com/elgohr/Publish-Docker-Github-Action/runs/1161676050?check_suite_focus=true#step:4:174
