### ISSUE TITLE
[BUG] tag_names and tag_semver do not work as documented

### ISSUE THREAD

**Issue by serucee** [elgohr/Publish-Docker-Github-Action#104]
**Describe the bug**
When using tag_names or tag_semver on release [published] the image keeps getting tagged with :latest

**To Reproduce**
Run elgohr/Publish-Docker-Github-Action@2.22
  with:
    name: image-name
    username: ***
    password: ***
    registry: private-registry
    dockerfile: Dockerfile
    tag_names: true

or tag_semver: true

Output/Result:
Successfully built 75a374fb7fce
Successfully tagged private-registry/image-name:latest
The push refers to repository [private-registry/image-name]

**Expected behavior**
With tag_names i expect the image to be tagged with the git name as described in https://github.com/elgohr/Publish-Docker-Github-Action#tag_names
With tag_semver i expect the image to be tagged with the proper semver as described in https://github.com/elgohr/Publish-Docker-Github-Action#tag_semver

**Additional context**
Tested with @master and v2.22,  v2.2.1
As a workaround im now using "tags: "latest,${{ env.RELEASE_VERSION }}"" - this works flawless

**Comment by elgohr** [comment]
Sorry, can't reproduce, as the integration test covers this and is ok https://github.com/elgohr/Publish-Docker-Github-Action/actions/runs/270972745

**Comment by elgohr** [comment]
Ah wait, do you create a tag for that release or not?

**Comment by serucee** [comment]
I create a release via github which creates a tag in the background. The checked out branch according to the logs is a tag as well.

**Comment by serucee** [comment]
If i have time tomorrow i will recreate the behaviour in a public repo/debug a bit more.
