### ISSUE TITLE
[FEATURE] build multi-arch image

### ISSUE THREAD

**Issue by dragoneena12** [elgohr/Publish-Docker-Github-Action#106]
**Is your feature request related to a problem? Please describe.**
This Action seems to be able to publish only amd64 image.
I want multi-arch image(i.e. armhf or arm64).

**Describe the solution you'd like**
I think we can use `docker buildx`.

**Comment by elgohr** [comment]
At the moment you could use a self-hosted runner, but I agree that this would be a great feature.

**Comment by dragoneena12** [comment]
ty! I'll work on this.

**Comment by sundowndev** [comment]
Would love to get that feature too, did you get to dig into this @dragoneena12 ?

**Comment by dragoneena12** [comment]
@sundowndev Now I'm using [docker/build-push-action](https://github.com/docker/build-push-action) instead.

**Comment by elgohr** [comment]
Sorry, didn't see that this was auto-closed.

**Comment by elgohr** [comment]
Please give it a try: https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/3.03
I'm not sure about pushing the images at the moment - as I found no documentation.
Need to investigate whether `-push` in `docker buildx build` is necessary or whether this could also be done by using good old `docker push`.

**Comment by a1300** [comment]
@elgohr I am running this action with `elgohr/Publish-Docker-Github-Action@master`
I tried running this on `ubuntu-18.04` and `ubuntu-20.04`. Both times I got the error 

```
dd: can't open '/etc/docker/daemon.json': No such file or directory
```

I used the new property `platforms: linux/amd64,linux/arm64`. I am hesitant to share the full config due to security considerations.

Do I need to do an extra setup to make `docker buildx` and `platforms` work?

**Comment by elgohr** [comment]
Hey @a1300 , will have a look.
Do you get this for both Ubuntu versions?

**Comment by a1300** [comment]
@elgohr yes on both ubuntu versions

**Comment by a1300** [comment]
@elgohr do you know an example project that uses the new `platforms` option ?

**Comment by elgohr** [comment]
At the moment this feature is in beta (see Release Notes). In this way I'm still exploring the field.
Looks like we got some challenge here : https://github.com/actions/virtual-environments/issues/3090

**Comment by elgohr** [comment]
Sorry to say that I reverted this for now.
At the moment I have not that much time for tinkering (as you can see in the other issue, it's just tinkering).
I also increased the time for issues not becoming stale https://github.com/elgohr/Publish-Docker-Github-Action/commit/be0a327a5b402db8600d8d2afa83ecc23b2d9a6e

**Comment by elgohr** [comment]
Finally I managed to recover some time.
Would be great if you could beta test 

```
- name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@multiarch
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        platforms: linux/amd64,linux/arm64
```

**Comment by yangyangdaji** [comment]
ping

**Comment by elgohr** [comment]
Please have a look at https://github.com/elgohr/Publish-Docker-Github-Action#platforms

**Comment by mcpierce** [comment]
I'm trying this feature and am not having luck: it's only publishing a linux/amd64 image and I would love to have linux/arm64 as well. Any suggestions?

**Comment by elgohr** [comment]
@mcpierce  could you please provide your configuration?

**Comment by mcpierce** [comment]
@elgohr I spent some time last night working on this issue in my project and found an alternative path for publishing multi platform. Thanks for the quick response.
