### ISSUE TITLE
Docker login best practice

### ISSUE THREAD

**Issue by pascalandy** [elgohr/Publish-Docker-Github-Action#11]
instead of https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/entrypoint.sh#L36

I suggest:

```
echo $(cat ${secret_token}) | docker login --username ${secret_user} --password-stdin;
```

Cheers!

**Comment by elgohr** [comment]
Thanks for the review!
Missed it in the quick fix from yesterday.
Will fix it, as soon as I have dev station nearby.
If you feel lucky you could also open a PR.

**Comment by elgohr** [comment]
There you go https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/1.7

**Comment by pascalandy** [comment]
You're welcome! I prefer to ping people first then do a PR :)
And thanks for sharing this. Works well so far so good :)
