### ISSUE TITLE
Hey, thank you for the PR.

### ISSUE THREAD

**Issue by Johnnyb531** [elgohr/Publish-Docker-Github-Action#129]
Hey, thank you for the PR.
Can you still reproduce this issue today?

__Originally posted by @elgohr in https://github.com/elgohr/Publish-Docker-Github-Action/pull/119#issuecomment-813058918__

**Comment by Johnnyb531** [comment]
I'm new to this site I hope I didn't do mess anything up

**Comment by elgohr** [comment]
Please stop spamming issues
