### ISSUE TITLE
Tag and versionning

### ISSUE THREAD

**Issue by pascalandy** [elgohr/Publish-Docker-Github-Action#13]
I like your projet so far :)

### the challenge

By using this tag `username/myapp:32c812f7bc5e67f52f57ce80d236e70be601aaf9` we expose ourselves to troubles.

```
username/myapp:32c812f7bc5e67f52f57ce80d236e70be601aaf9
username/myapp:latest
```

With a CI build every day, even by using `username/myapp:32c812f7bc5e67f52f57ce80d236e70be601aaf9`, a build may have an issue and break things in production. 

By introducing a specific **date**, it would resolve this potential risk.

### suggestion

I'm curious to know if you would like to use this approach for tagging:

```
username/myapp:2.29.1-2019-08-24-23h43-32c812f7
```

**all tags**

```
username/myapp:2.29.1-2019-08-24-23h43-32c812f7
username/myapp:2.29.1-32c812f7bc5e67f52f57ce80d236e70be601aaf9
username/myapp:2.29.1
username/myapp:stable
```

Let me know :)

**Comment by elgohr** [comment]
Could you please go a little more into detail, why using the git sha could be a risk for production?

**Comment by pascalandy** [comment]
I glitch can happen between DATE X and DATE Y. A package is buggy but the build works. Then something crash and you can't compare between two images because everyday, you override `username/myapp:32c812f7bc5e67f52f57ce80d236e70be601aaf9`.

Make sense?

> With a CI build every day, even by using username/myapp:32c812f7bc5e67f52f57ce80d236e70be601aaf9, a build may have an issue and break things in production.

**Comment by pascalandy** [comment]
P.S. I see you are an engineer at VW. Can we talk about the EQ? The issue is that there are way to many clicks I have to do before I can EQ the sound. I need to have an **EQ** button. Just replace it with the Voice (unneeded button). 
The EQ is the function I use after the volume.

![Screen Shot 2019-08-24 at 5 24 21 PM](https://user-images.githubusercontent.com/6694151/63642868-2d5c6480-c694-11e9-8c57-d2414619c067.jpg)

**Comment by elgohr** [comment]
https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/1.8 there you go.
Currently I'm not working on radios, sorry :-)
