### ISSUE TITLE
[FEATURE] Do not overwrite existing images

### ISSUE THREAD

**Issue by brandon-piner-aruba** [elgohr/Publish-Docker-Github-Action#131]
**Is your feature request related to a problem? Please describe.**
We set the image tag from another file containing the version. If the workflow runs but the version did not change then the container image is overwritten in the container repo. This is bad practice if we are using the image in production. The image should be immutable.

**Describe the solution you'd like**
As part of our workflow, we push the docker image to a registry with specific version tags based on software changes. There is a chance that the image is being used in production so we never want to override an existing image.
If the change did not warrant a version change (updated docs, README, linting) then the pull request will close with the same version tag. 
Setting the check_existing option will abort any image push if one of the tags (excluding latest) exists in the registry

**Describe alternatives you've considered**
Using autogenerated tags - This does not help because we are setting the tag version from the helm chart appVersion. The helm chart Chart.yaml is the source of truth for the image tag.

**Comment by elgohr** [comment]
You could use https://github.com/elgohr/Publish-Docker-Github-Action#no_push for that.
By the way, having an immutable registry for production would be a far better practise.

**Comment by brandon-piner-aruba** [comment]
If you have a different understanding then please elaborate because `no_push` requires another workflow step to perform the check of whether the image tag exists. If it is in another workflow step then we need to do `docker login` before this github action. Is this what you where suggesting?

Which registry do you know that supports immutability? The only method I can see to get immutable tags is to the use SHA digest. That does not work with out use case

**Comment by elgohr** [comment]
Yes.

Otherwise you could also just run the step on tagged commits.
```
- name: Publish to Registry
  uses: elgohr/Publish-Docker-Github-Action@master
  if: startsWith(github.ref, 'refs/tags/')
```

> Which registry do you know that supports immutability?
Many
https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html
https://jfrog.com/blog/jfrog-artifactory-secure-private-docker-registry-in-production/
...

**Comment by brandon-piner-aruba** [comment]
Okay thanks for taking the time. We use Quay which does not seem to support immutability but I could be wrong still. 
We will just continue to run a fork which serves our need
