### ISSUE TITLE
[BUG] docker:20.10.8 seem to break the test.bats

### ISSUE THREAD

**Issue by kehao95** [elgohr/Publish-Docker-Github-Action#134]
**Describe the bug**
I've been using the master action for a while. It suddenly break for me. I tried most recent release `3.04` which works fine.
So the recent changes https://github.com/elgohr/Publish-Docker-Github-Action/compare/3.04...master may have introduced a bug.

### Failed on Build container for action use
It looks like it failed on [Dockerfile#L17](https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/Dockerfile#L17)

`Step 12/13 : RUN /test.bats`

partial error logs:
```log
  Step 9/13 : ADD test.bats /test.bats
   ---> 6f0705b7f549
  Step 10/13 : ADD mock.sh /usr/local/bin/docker
   ---> a4e437bed22a
  Step 11/13 : ADD mock.sh /usr/bin/date
   ---> fb7ee6d4aad2
  Step 12/13 : RUN /test.bats
   ---> Running in 81fa579a8d29
  1..46
  /usr/bin/date: line 12: mockReturns: No such file or directory
  /usr/bin/date: line 13: /usr/bin/date: syntax error: operand expected (error token is "/usr/bin/date")
  /usr/bin/date: line 12: mockReturns: No such file or directory
  /usr/bin/date: line 13: /usr/bin/date: syntax error: operand expected (error token is "/usr/bin/date")
  /usr/libexec/bats-core/bats-exec-test: line 127: * 1000 : syntax error: operand expected (error token is "* 1000 ")
  /usr/lib/bats-core/tracing.bash: line 61: BATS_STACK_TRACE: bad array subscript
  not ok 1 
  /usr/bin/date: line 12: mockReturns: No such file or directory
  /usr/bin/date: line 13: /usr/bin/date: syntax error: operand expected (error token is "/usr/bin/date")
  /usr/bin/date: line 12: mockReturns: No such file or directory
  /usr/bin/date: line 13: /usr/bin/date: syntax error: operand expected (error token is "/usr/bin/date")
  /usr/libexec/bats-core/bats-exec-test: line 127: * 1000 : syntax error: operand expected (error token is "* 1000 ")
  not ok 2 
  ...
   not ok 45 
  /usr/bin/date: line 12: mockReturns: No such file or directory
  /usr/bin/date: line 13: /usr/bin/date: syntax error: operand expected (error token is "/usr/bin/date")
  /usr/bin/date: line 12: mockReturns: No such file or directory
  /usr/bin/date: line 13: /usr/bin/date: syntax error: operand expected (error token is "/usr/bin/date")
  /usr/libexec/bats-core/bats-exec-test: line 127: * 1000 : syntax error: operand expected (error token is "* 1000 ")
  not ok 46 
  /usr/lib/bats-core/tracing.bash: line 61: BATS_STACK_TRACE: bad array subscript
  The command '/bin/sh -c /test.bats' returned a non-zero code: 1
```

### BATS_STACK_TRACE: bad array subscript
So it looks like the root cause was on `bats`
by checking the log I found on 
for `Step 8/13 : RUN apk add --no-cache coreutils bats` will install different versions of bats. Which may lead to this error.

on **master(docker:20.10.8)**  it will install `bats (1.3.0-r0)`
on **release-3.04(docker:20.10.6)** it will install `bats (1.2.1-r0)`

This may related to https://github.com/bats-core/bats-core/issues/350

Sorry I'm not familiar with bats can't provide more details.

## suggestions:
We may either rollback docker version or [pin the right bats version to be apk added](https://superuser.com/questions/1055060/how-to-install-a-specific-package-version-in-alpine)

Thank you for this awesome project.

**Comment by luongvancong** [comment]
Same question

**Comment by luongvancong** [comment]
Change workflow config from: uses: elgohr/Publish-Docker-Github-Action@master to uses: elgohr/Publish-Docker-Github-Action@3.04

Error fixed.

**Comment by elgohr** [comment]
Thank you for reporiting.
https://github.com/elgohr/Publish-Docker-Github-Action/commit/559e1a452e455206c72baf0a76bf8097cfa6277c should fix this. Could you please verify?

**Comment by geokaragiannis** [comment]
it works for me now. Thanks!

**Comment by elgohr** [comment]
Great, will investigate later why dependabot merged this, even if this was breaking.
Until then I removed dependabot

**Comment by lemonsaurus** [comment]
Excellent, this failed for me 4 hours ago, I went out to eat lunch, got pulled into a few meetings, and now I was going to investigate why it was failing. Went to this repo to look for a relevant issue, and found out that you've already fixed it. Ran my workflow again, it works now!

Thanks for addressing this so quickly, @elgohr, I appreciate it! 👏🏼

**Comment by elgohr** [comment]
I had a deeper look how it came to this.
Tests in CI had been perfectly fine with dependabot (https://github.com/elgohr/Publish-Docker-Github-Action/runs/3293782587).
But it looks like 20.10.8 has been overwriten yesterday
![image](https://user-images.githubusercontent.com/19632501/131916253-0d1dae20-7000-497b-a1fd-d8b860e34630.png)
The new image is using alpine 3.14 (which is using bats 1.3.0 - which is having some problems).
In this way `docker:20.10.8-alpine3.13` builds fine - `docker:20.10.8-alpine3.14` doesnt.

**Comment by elgohr** [comment]
Let's see how this goes :)
https://twitter.com/lagohr/status/1433538842972221455?s=20

**Comment by stck** [comment]
@elgohr Still seems like a temporal solution. Do you have any plans moving new version of bats? Some Roadmap for example?

**Comment by elgohr** [comment]
At the moment I'm thinking about reverting https://github.com/elgohr/Publish-Docker-Github-Action/commit/91a3945f7b649ffd5186bcd966ed964e35f52b09 to the homebrewn solution in favor of bats for testing. This would also result in faster build speed - but it would also make testing more complex...

**Comment by elgohr** [comment]
Will be fixed

**Comment by elgohr** [comment]
Finally fixed in https://github.com/elgohr/Publish-Docker-Github-Action/commit/99d870b29e035da095b630703e866ae9fc484f3a
