### ISSUE TITLE
Support pull before build

### ISSUE THREAD

**Issue by xmatthias** [elgohr/Publish-Docker-Github-Action#14]
I think this action should support optionally pulling the previous image before building (as an option).

This can tremendously speed up slow builds, since it doesn't have to build all layers from scratch. 
Also, shared layers reduce download time (on frequently updated images), since most of the image is already present when upgrading to "latest".

We currently use this with Travis to do daily builds (and once per week, a full image is rebuild, to keep the base uptodate). 

Sample implementation:
``` bash
 docker pull ${IMAGE_NAME}:${TAG}
 docker build --cache-from ${IMAGE_NAME}:${TAG} -t ${IMAGE_NAME}:${TAG} .
```

**Comment by elgohr** [comment]
![56078d02c0735175](https://user-images.githubusercontent.com/19632501/63748043-daa7c600-c8a8-11e9-864b-88e64dfde900.jpg)
So how would cache invalidation work?

**Comment by xmatthias** [comment]
for travis, it's based on event type - if it's a scheduled job (scheduled in travis to run once a week).

I don't know enough about github actions yet (and documentation about the new yaml syntax is sparse / difficult to find) to determine if it offers scheduled jobs (but i would assume it does).

```bash
if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then
    echo "event ${TRAVIS_EVENT_TYPE}: full rebuild - skipping cache"
    docker build -t ${IMAGE_NAME}:${TAG} .
else
    echo "event ${TRAVIS_EVENT_TYPE}: building with cache"
    # Pull last build to avoid rebuilding the whole image
    docker pull ${IMAGE_NAME}:${TAG}
    docker build --cache-from ${IMAGE_NAME}:${TAG} -t ${IMAGE_NAME}:${TAG} .
fi
```

**Comment by elgohr** [comment]
So if the scheduled task ignores external changes (by caching the layer), what is it for?

**Comment by xmatthias** [comment]
The scheduled task (the line and within the if-statement after the line containing `"cron"`) in the above code-snipped rebuilds the full image from scratch (all layers).

The "regular" build only builds the changes done to my application based on the merge that just happened. External dependencies in higher layers are only refreshed once per week.

This workflow will not be needed for simple images - but for applications with resulting images > 1Gb this can be a huge speedup for both the building time (CI run time) and the download-sizes -> download times for users.

Based on your answers, i assume you work with mostly light images, where this is not a huge issue? (build quickly, don't have long compile times)

**Comment by elgohr** [comment]
Okay, so the other way around. 

Makes sense to me, if everybody would do it that - but that's not the case.

Without the cron-build it would end up in frozen external dependencies.

This could be an option for configuration, like `cached: true`, but I don't think that it would be default.

**Comment by xmatthias** [comment]
Oh I never wanted to have this default, sorry if you understood it that way, that would not make sense, not for small / quick building images.

I'm very well aware that this is a edgy case, what i would like to have is to have this as an option, which can be enabled (and which should clearly state/document that it should then also be triggered by a cron-job to not have external dependencies frozen).

**Comment by elgohr** [comment]
There you go https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/1.10

**Comment by xmatthias** [comment]
Thanks a lot! :+1:
