### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by imreg** [elgohr/Publish-Docker-Github-Action#143]
Guys, what's going on in this repos now. What is this limbo between master and main?

Our team receive an error:
```
Build Opus API Service
Unable to resolve action `elgohr/Publish-Docker-Github-Action@main`, unable to find version `main`
```

**Comment by elgohr** [comment]
Hey, sorry for the inconvenience. There had been a limbo in the past - due to the fact that most people don't use versioning and still rely on master it was changed back to master. Please use this one or a release version.

**Comment by imreg** [comment]
We have had issues few months ago when this service was changed to main. And then all our repos were maintained for using main branch in our system, and all now has same issue because you moved back.

In this case, please create a branch with name: main, because of many company and people already use main. 
Please do a predictable and reliable system!

This is what was written previously here:
https://github.com/github/renaming

**Comment by elgohr** [comment]
This was moved back because of an issue months ago. I only kept the `main` branch for transition.
I put it back now, so you can make a smooth transition to `master`.

**Comment by elgohr** [comment]
@imreg added a hint to the logs. I guess we can close this here https://github.com/elgohr/Publish-Docker-Github-Action/commit/8217e91c0369a5342a4ef2d612de87492410a666
