### ISSUE TITLE
Failed Build Marked As Step Passed 

### ISSUE THREAD

**Issue by deef0000dragon1** [elgohr/Publish-Docker-Github-Action#15]
Using the action in a build. When the action is triggered, the publish to registry has "ADD failed" occur.  
This stops the dockerfile execution, then 
```
An image does not exist locally with the tag: ***/repo
The push refers to repository [docker.io/***/repo]
Removing login credentials for https://index.docker.io/v1/
```

and then the step (and thus job) is marked as check passed.

**Comment by elgohr** [comment]
Could you please add your configuration?

**Comment by elgohr** [comment]
Should have been fixed https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/1.9
