### ISSUE TITLE
[BUG] ::set-output deprecated in actions

### ISSUE THREAD

**Issue by coldino** [elgohr/Publish-Docker-Github-Action#167]
**Describe the bug**
Thanks very much for this action. Been using it for a while now and just noticed the following in my logs:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Additional context**
The linked [notice](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) says the currently used method will stop working 31st May 2023, but has a pretty simple fix. Unfortunately, that means anyone who pins the version of this action will be in for a surprise on that date.

**Comment by elgohr** [comment]
Hi,
as you can see in https://github.com/elgohr/Publish-Docker-Github-Action/commit/93655185f260b851ede78d9a57760a8bbda65f68 this action supports the new syntax since the day it was announced.
Nevertheless the action also supports the old syntax, as this would be a breaking change otherwise.
In this way people can have a smooth transition in their workflows.

I will keep this issue open until the 31st May 2023, so that we avoid duplicates.

**Comment by coldino** [comment]
Ah, thank you. I did search issues and check the main branch, but apparently this fix is elsewhere. Thanks for your continued work.

**Comment by phnx47** [comment]
@elgohr Hi! I checked commit, you switch from Output to Env. But can continue use Output with new syntax: `echo "{name}={value}" >> $GITHUB_OUTPUT`. It will be not breaking changes. Any reason why you want move to Env instead of Output?

**Comment by elgohr** [comment]
@phnx47 good catch - no, this is a bug. Would be happy for a PR.

**Comment by phnx47** [comment]
@elgohr Oh, sorry, you edited message. I will raise one more PR

**Comment by phnx47** [comment]
@elgohr 

Just replaced GITHUB_ENV -> GITHUB_OUTPUT: https://github.com/elgohr/Publish-Docker-Github-Action/pull/171

Here I removed legacy output, you can check it too: https://github.com/elgohr/Publish-Docker-Github-Action/pull/170

**Comment by elgohr** [comment]
Please see https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/v5
