### ISSUE TITLE
[BUG] Old tag confuses automated dependency updaters

### ISSUE THREAD

**Issue by ivuorinen** [elgohr/Publish-Docker-Github-Action#169]
**Describe the bug**

Tag `20190331160914` confuses automated dependency updaters (renovate in my case) as it's _a larger number_ than current version 4 🤷

**To Reproduce**

See https://github.com/ivuorinen/docker-php-with-imagick/pull/3

**Expected behavior**

As v4 is the latest, I wasn't expecting tool to offer a version from 2019 as the latest. 

**Additional context**

Thank you for maintaining this Action, it's making my life (and I'm sure for maaaany others) so much easier.

**Comment by elgohr** [comment]
Hey, thank you for bringing this up. 
Wasn’t aware of that. I’ll have a look.
At the moment I’m not really sure how to fix it, as deleting the unexpected tag could break people’s builds…

**Comment by elgohr** [comment]
I decided to delete `20190331160914` as it was really a pre-historic release and people that depend on it should update anyway, for security reasons.

**Comment by elgohr** [comment]
I also cleaned up the other tags/releases that were not semver-compliant. They had been from years ago.

**Comment by ivuorinen** [comment]
Thank you! The automation works now as expected, Closing this as resolved.
