### ISSUE TITLE
GitHub Registry

### ISSUE THREAD

**Issue by tombowditch** [elgohr/Publish-Docker-Github-Action#17]
Hi all,

Anyone had any success getting this working with GitHub's Registry? I'm just getting auth errors...

```
denied: requested access to the resource is denied
##[error]Docker run failed with exit code 1
```

**Comment by elgohr** [comment]
Please see https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/.github/workflows/test_integration_github.yml

**Comment by tombowditch** [comment]
That worked, cheers.
