### ISSUE TITLE
Ref Tags Can Break Build

### ISSUE THREAD

**Issue by hamelsmu** [elgohr/Publish-Docker-Github-Action#18]
Here is an example:

```
invalid argument "docker.pkg.github.com/github/hamel-learn-actions/issue-label-
model:refs/pull/24/merge" for "-t, --tag" flag: invalid reference format
```

input yaml:

```
    - name: Publish Container to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with: #Publish to GPR
        name: docker.pkg.github.com/github/hamel-learn-actions/issue-label-model
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: argo/Dockerfile-gpu
        registry: docker.pkg.github.com
        snapshot: true
```

**Comment by elgohr** [comment]
Maybe a duplicate?

**Comment by hamelsmu** [comment]
yes looks like a duplicate.  Sorry about that, closing the issue.

**Comment by elgohr** [comment]
@hamelsmu what would be your expectation for PRs?

**Comment by hamelsmu** [comment]
I would like something that pushes an image tagged with the SHA.   Sometimes I need to run a test with the context of the branch of the PR and deploy the application to test cluster.

If it doesn't make sense to you, please let me know.  I read the other thread where you did not recommend testing things this way - would love to hear you expand on that for my own curiosity.

Of course, if you do not want to support this, I completely understand.  Thank you for sharing your code.  

Thanks!

**Comment by elgohr** [comment]
I can totally understand that. I just want to be responsible for introducing a security risk for people. Is there a way to differentiate between PRs to yourself and to others?

**Comment by elgohr** [comment]
Please try this and give feedback https://github.com/elgohr/Publish-Docker-Github-Action#pull_requests

**Comment by hamelsmu** [comment]
Can you tell me more about security concerns?  What are you afraid that might happen?  Can you give me an example of how this could be a vulnerability?

**Comment by elgohr** [comment]
Pull requests often happen between two parties. Both parties need to have their secrets configured.

Nevertheless the context where the secrets are coming from changes in the process.
Some people use linters to prevent that secrets are logged or shown elsewhere.
This would not be possible in a pull request (as the repository is still in anothers person context) and would only be happening after the first build (which could probably expose the credentials, if people aren't looking carefully).

So this is a general thing - why do I care especially? Because this resource, as it publishes to the registry, might go directly into production.

**Comment by hamelsmu** [comment]
Interesting as far as I know people who do not have write access to the repository can use your secrets https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables

This means people making a PR by forking their own branch will not be able to see secrets and for those people, the Action would break (which is a good thing) if for example they try to use Docker credentials stored in your secrets file 

It is possible that someone with direct write access that you grant to your repo can do something malicious but they could do that anyways I suppose?  

I agree that for avoiding headaches it is up to the author to clearly segregate between test and production environments including how Docker images are promoted to production.  I’m curious if I have missed anything else that was concerning you regarding security?  Thanks for your comments

**Comment by elgohr** [comment]
I'm thinking about the time after you say "PR across forks". If this action has to be green for mergin, people have to provide credentials. Wouldn't this mean that the person, which receives the PR, would have write access to this (I remember a hook, which is set by default) repository and could propagate any change in the name of the contributer?

**Comment by hamelsmu** [comment]
Ok I understand what you are saying now. Yes I suppose people would have to provide credentials but I don’t think they should, because that seems like an unreasonable security risk. I don’t have a good solution that comes to my mind right away. Let me think about it more

**Comment by elgohr** [comment]
I close this here. We continue in https://github.com/elgohr/Publish-Docker-Github-Action/issues/24
