### ISSUE TITLE
Slash in branch name breaks docker tagging

### ISSUE THREAD

**Issue by batpad** [elgohr/Publish-Docker-Github-Action#22]
It is quite a common convention to name branches like `feature/foo` - unfortunately, having a slash in the branch name seems to break docker tagging:

I get an error like:

    invalid argument "batpad/fake-repo-name:feature/foo" for "-t, --tag" flag: invalid reference format

I am fairly certain this is caused due to the `/` in the branch name -- in the above scenario, the branch is `feature/foo`.

Honestly, I'm not sure what the best thing to do here might be - just stripping slashes or replacing them with dashes seems like it would fix it, but it also seems like a bit of an awkward solution.

Happy to work on a PR if there is an agreement on whether this is an actual issue and what the best solution is.

Of course, my apologies if I missed an existing issue about this. Thank you for this project.

**Comment by elgohr** [comment]
Hey, replacing the slash with the hyphen sounds good to me.
At the moment I'm working on a rewrite in go, as the actions seems to get more and more complex. In this way it would be nice if you could add this as a PR (please don't forget the tests)

**Comment by pabrams** [comment]
The slashes are useful to create folders, though.
