### ISSUE TITLE
Setting working directory

### ISSUE THREAD

**Issue by automada** [elgohr/Publish-Docker-Github-Action#23]
Testing out actions for the first time, and this one fits perfectly into my flow. Great work! At some point I came across an issue where I needed to change the working directory based on needs in the dockerfile. I tried to search for it as a generic feature in actions, but it seems like this is something that each action must solve internally?  I forked your repo and added:

```
if [ ! -z "${INPUT_WORKDIR}" ]; then
  cd ${INPUT_WORKDIR}
fi
```

to entrypoint.sh. This allowed me to set the correct directory when running the action. Not sure if this is the correct way to solve this. Any input would be much appreciated. 

Thanks!

**Comment by remorses** [comment]
You can use the path input in the checkout step
```yml
    steps:
    - uses: actions/checkout@v1
      with:
        path: your_path
```
All the steps after that should use that path as the working directory

**Comment by elgohr** [comment]
Thank you for the request and fast response ☺️
Didn't know about the path in the checkout either. I guess we can close it?

**Comment by automada** [comment]
That was quick! Thanks for the response and tip. I tried setting the path, but it seems to only append it to the path context:

`/home/runner/work/myrepo/added_in_path`

The actual workdir is the same (not sure about the use case for this). I did a `pwd ` inside the action, and it lists the same content even after the path is set.

I also looked at the `working-directory` variable, but that doesn't seem to work with the `uses` statement:

https://github.community/t5/GitHub-Actions/Github-actions-working-directory-incorrectly-documented/td-p/29201

Maybe I'm missing something here, but I still cannot see another solution that to pass the path in to the action.

**Comment by elgohr** [comment]
I'm trying to get an answer from Github whether there is a way to contribute to the checkout plugin, as this seems to be the one doing the actual checkout. At my point more actions could benefit from this, when it's in the checkout.

**Comment by automada** [comment]
Sounds like a good plan. I agree that this is a feature that more would benefit from. That is why I almost took it for granted. Hence the feeling I'm missing a feature that already exist :)

**Comment by alexnuttinck** [comment]
Hello,

I face the same problem. My Dockerfile is generated in another step after the checkout step. So, the `path input` fix doesn't work for my case.

The additions made by @automada makes sense for me. But I think it would be better if we can use the working-directory variable with the uses statement.

**Comment by remorses** [comment]
This seems a bug with the `chckout` action `path` option:
when running actions containers there are 2 volumes are mounted on the same directory:
```
/usr/bin/docker run ...
-v "/home/runner/work/_temp/_github_workflow":"/github/workflow"
 -v "/home/runner/work/repository/{the path option inside checkout plugin}":"/github/workspace" 
```
I think the first volume links to the repository root and hides the second volumes that would link to the right directory specified in the `checkout` action

**Comment by elgohr** [comment]
I guess having `workdir` in checkout might take some time.
In this way I introduced it here, so that people can already work.
When it's introduced in checkout, it will be deprecated.
See https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/1.13 and https://github.com/elgohr/Publish-Docker-Github-Action#workdir

**Comment by automada** [comment]
That is great @elgohr! Thanks for the follow-up and fix :thumbsup:

**Comment by alexnuttinck** [comment]
Thanks @elgohr!
