### ISSUE TITLE
Feature Request: Push a local (already existing) image 

### ISSUE THREAD

**Issue by ichtestemalwieder** [elgohr/Publish-Docker-Github-Action#25]
Hello, 

thanks for the project. 

According to the docs I expected the plugin to only push existing local Images to the Repository. But I realized it also builds the Image. Maybe it would be good, to offer an option to choose if 
a) the image should be build and published 
b) an existing local image should be published (and not be build)
Thanks very much!

**Comment by elgohr** [comment]
Hi,
an action tries to simplify things.
Why don't you use `docker push` in that case?

**Comment by elgohr** [comment]
This request would complicate the action a lot, as there had to be an extra step for checking the present local images for "pushability"(if that's a word).
There would also be the need of something like a contract how the build must happen (e.g. see the format of `snapshot` tags).
At my point of view this adds to much complexity. In this way I would like to decline the request, if you don't have a usecase which wouldn't be buildable with this resource.

**Comment by ichtestemalwieder** [comment]
Thanks for your answer. Very good point! I absolutely understand your answer. 

As your Action is found via docker searchterm in the GH Action Marketplace I assumed I should have to use it and its the recommended way to publish an image. 
But thanks to your answer I realized I can very easliy, with only two "run" commands, do everything manually. Maybe this would be worth mentioning in your readme that it is a "wrapper" to "docker build" and "docker publish" that could also easily be used. I was not aware of this. Thanks!
