### ISSUE TITLE
[Request] Output tag names

### ISSUE THREAD

**Issue by jhoward321** [elgohr/Publish-Docker-Github-Action#26]
Since you already have the logic to generate the tag name, would it be possible to add an output variable where those tag names can be referenced in later actions?

I need to specify to kubernetes which docker tag to use. I can write my own shell script to duplicate your logic, but it would be awesome if I could just grab it using a variable such as 

${{ steps.upload_docker.outputs.tag }}

**Comment by elgohr** [comment]
There you go. I assume you didn't mean `lastest` :)
https://github.com/elgohr/Publish-Docker-Github-Action#outputs

**Comment by jhoward321** [comment]
Thank you! This has been the most useful action I've found by far
