### ISSUE TITLE
how do you copy output from another job into this one?

### ISSUE THREAD

**Issue by NullVoxPopuli** [elgohr/Publish-Docker-Github-Action#27]
I have another job in my workflow that publishes to a CDN I'd like to take the output from that and throw it into the publish docker step -- it doesn't make sense for me to build my app twice, ya know?

**Comment by elgohr** [comment]
If you already make the effort to upload to a CDN, a docker push shouldn't be that much more...
Sorry, but this sounds like an edge case to me.

**Comment by NullVoxPopuli** [comment]
Well, previously, when I was on gitlab, and just using bash, I'd already have my build artifacts, so there was no need to rebuild. Additionally, this ensured that what was on the CDN was also available in the docker image.


Sorry, this is not an edge case! 

GitHub has the ability to have artifacts even... Via actions/upload-artifact

**Comment by NullVoxPopuli** [comment]
![image](https://user-images.githubusercontent.com/199018/65802134-9e79b680-e12f-11e9-9737-7e123025d6ff.png)

just need a way to download them before running `docker build`

**Comment by NullVoxPopuli** [comment]
though, if this works: https://github.com/NullVoxPopuli/emberclear/blob/master/.github/workflows/frontend-deploy.yml#L64

that'd be fine, too

**Comment by elgohr** [comment]
You could try using `cache` (https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/README.md#cache) for that. But it will not be supported. Please see the other issue for reasons

**Comment by NullVoxPopuli** [comment]
It's not a big image / cache problem, it's more of a an assurance / certainty thing. The assets are already built, so those assets must be what goes in the image

**Comment by NullVoxPopuli** [comment]
looks like my workflow works. Secret is upload/download artifact actions. neat

**Comment by elgohr** [comment]
I took a look at your pipe. You could get the same with multi-staged docker containers
(see https://github.com/elgohr/cf-jetbrains-license-server/blob/master/Dockerfile as an example). This would work with this action.

**Comment by NullVoxPopuli** [comment]
I know multi stage builds would work, but they aren't what I want. :);

I have what I want now ;)
