### ISSUE TITLE
Error with latest version

### ISSUE THREAD

**Issue by kunal52** [elgohr/Publish-Docker-Github-Action#32]
##[error]/home/runner/work/_actions/elgohr/Publish-Docker-Github-Action/master/action.yml:
##[error]/home/runner/work/_actions/elgohr/Publish-Docker-Github-Action/master/action.yml: (Line: 34, Col: 2, Idx: 1103) - (Line: 34, Col: 2, Idx: 1103): While parsing a block mapping, did not find expected key.
##[error]Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
##[error]Fail to load /home/runner/work/_actions/elgohr/Publish-Docker-Github-Action/master/action.yml

**Comment by elgohr** [comment]
Should have been fixed now.
Please verify

**Comment by elgohr** [comment]
Finished the move to `action.yml`, as this seems to be the newest way to go for actions...
Sorry for the inconvenience, everything should be working as expected.

**Comment by kunal52** [comment]
Yes, It's working fine. 
Thanks for the great work.
