### ISSUE TITLE
No way to apply a label?

### ISSUE THREAD

**Issue by rokcarl** [elgohr/Publish-Docker-Github-Action#35]
I would like to push to `latest` but would like a way to check the git sha of the image. What I've done in the past is to build the image with `--label org.opencontainers.image.revision=${{github.sha }}`, according to [open standard annotations](https://github.com/opencontainers/image-spec/blob/master/annotations.md).

But with this project, there's no way for me to apply such a label, I think.

**Comment by elgohr** [comment]
Please have a look at

**Comment by elgohr** [comment]
Big thumb on mobile. Sorry for closing

**Comment by rokcarl** [comment]
I've seen that. But that is just another tag. I would like my app to run the `latest` tag, so that I don't have to change what runs with every build. But if something goes wrong, I'd like to know what code (git sha) is inside that docker image. That's what I have the label for.

**Comment by elgohr** [comment]
Using `snapshot` the image will have both, `latest` and the snapshot tag.

**Comment by rokcarl** [comment]
I know. The `latest` one will not have a label though.

**Comment by elgohr** [comment]
Why would you need the label, if you have the tag?

**Comment by rokcarl** [comment]
> I would like my app to run the `latest` tag, so that I don't have to change what runs with every build. But if something goes wrong, I'd like to know what code (git sha) is inside that docker image. That's what I have the label for.

But I've resorted to just go with raw commands to build, it's only 15 lines in total. This is my build command:

    docker build -t user/repo:${{ github.sha }} -t user/repo --label org.opencontainers.image.revision=${{ github.sha }} .

**Comment by elgohr** [comment]
Ok, so I guess we can close this.
