### ISSUE TITLE
Build Context

### ISSUE THREAD

**Issue by ankitjain28may** [elgohr/Publish-Docker-Github-Action#48]
**Is your feature request related to a problem? Please describe.**
We have the change directory option, what if my Dockerfile is in the parent directory to docker build context content.

**Describe the solution you'd like**
with the argument as build-content, where we can set the content and default it is `.`

**Comment by ankitjain28may** [comment]
I can take this issue.

**Comment by elgohr** [comment]
Maybe I don't get it correct, but why wouldn't you do `workdir: ..`? https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/README.md#workdir

**Comment by ankitjain28may** [comment]
```
- abc (folder)
|- Dockerfile
|- xyz (build context for Dockerfile)
|- blah blah..
|- important stuff
|- Dockerfile2
|- xyz2 (build context for Dockerfile2)
```
Incase of workdir, we wont be able to left `xyz2` folder, so in case of build context argument, we can define abc as the workdir and specify Dockerfile along with build context. Hope it makes sense.

**Comment by elgohr** [comment]
Sorry, I don't get it.
The checkout would get `abc`, as that's the root. So there wouldn't be the need for `workdir: ..` anyway. You can define the Dockerfile by https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/README.md#dockerfile , which can reference the files in xyz or xyz2.

**Comment by ankitjain28may** [comment]
Please read this-> https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#understand-build-context
You will get a better idea about why it is required.

**Comment by elgohr** [comment]
Ok, let me sum this up.
There are multiple Dockerfiles inside a repository.
We want to build one of them and avoid sending the unneeded resources, which are probably needed by another Dockerfile, to the deamon.
We can't use .dockerignore , because this would also affect the other Dockerfiles builds.
So why can't we have 
```
- abc (folder)
|- xyz (build context for Dockerfile)
|-- Dockerfile
|- xyz2 (build context for Dockerfile2)
|-- Dockerfile2
```
and use `workdir` ?

I would like to avoid as much magic as possible...

**Comment by ankitjain28may** [comment]
If I change the change the workdir to `xyz`, it wont be able to find the location of Dockerfile as it is in the parent dir to `xyz`.

**Comment by elgohr** [comment]
So what limits you from moving it into `xyz`?

**Comment by ankitjain28may** [comment]
Well, that's not actually a solution.  There are cases where such scenarios occur and because of that docker has provided a build-context feature.

**Comment by elgohr** [comment]
Could you please make an example where this wouldn't be a solution?

**Comment by Lybecker** [comment]
I would like this feature too

**Comment by elgohr** [comment]
There you go https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/2.9
https://github.com/elgohr/Publish-Docker-Github-Action#context
