### ISSUE TITLE
[FEATURE] Action should output image digest (sha256)

### ISSUE THREAD

**Issue by chrishiestand** [elgohr/Publish-Docker-Github-Action#51]
**Is your feature request related to a problem? Please describe.**
For those of us who want to then deploy the image using the digest, having the output would be very convenient.

**Describe the solution you'd like**
The output should also include e.g. `digest` which would container e.g. `sha256:cbbf2f9a99b47fc460d422812b6a5adff7dfee951d8fa2e4a98caa0382cfbdbf`

**Describe alternatives you've considered**
Deploying by the tag is an option but may be suboptimal since tags are more easily mutable.
If I really want the digest I could use an additional step to read the digest out - this requires an unnecessary step.

**Comment by elgohr** [comment]
Did you consider using https://github.com/elgohr/Publish-Docker-Github-Action#snapshot?

**Comment by chrishiestand** [comment]
It's not really what I'm looking for. The digest is content addressable so I don't worry about it being overridden in any situation (as long as sha-256 collisions are nearly impossible).

**Comment by elgohr** [comment]
So you're saying the action could push it to a registry and get back the digest?
https://github.com/moby/moby/issues/32016

**Comment by elgohr** [comment]
Looks more fragile to me https://docs.docker.com/registry/compatibility/

**Comment by chrishiestand** [comment]
@elgohr yes, push and then return the digest as an output. The digest is being created anyway, why not return it so it may be used by the users, if we wish? And in my experience, it's not been fragile - Docker 1.10 has been out for 3.5 years and I'm not personally concerned about it.

But it's your project, feel free to `wontfix` this issue if it's not something you care for.

**Comment by elgohr** [comment]
Should be part of the next release

**Comment by chrishiestand** [comment]
Thank you. I expect this will make some people besides me happy as well :-)

**Comment by elgohr** [comment]
There you go https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/2.10
