### ISSUE TITLE
Question: DockerFile in nested folder

### ISSUE THREAD

**Issue by BillChirico** [elgohr/Publish-Docker-Github-Action#54]
Is it possible to specific a DockerFile within the repository?

Example: src/Web/DockerFile

**Comment by elgohr** [comment]
As you might have overseen the template, let me paste the interesting part

> Opening a bug report, you already tried to solve this issue yourself and can give detailed information in the underlying template. In this way everybody can benefit from this improvement.  

> If you just came here because you want to have a one-on-one configuration session, please consider contacting me directly, as my PayPal is wide open. I don't run this as a business. So all the money gained by this will go directly to https://www.welthungerhilfe.org . In this way I will add the improvement for everybody for you.
