### ISSUE TITLE
Integration with Azure Container Registry [FEATURE]

### ISSUE THREAD

**Issue by briglx** [elgohr/Publish-Docker-Github-Action#56]
**Is your feature request related to a problem? Please describe.**
Please include info on Azure Container Registry

**Comment by elgohr** [comment]
Looks like it's already usable and mainly needs to be configured in Azure (https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal). Probably we could document this

**Comment by elgohr** [comment]
Did you try that?

**Comment by elgohr** [comment]
@briglx could you please tell me what happens when you call https://docs.microsoft.com/en-us/cli/azure/acr/token?view=azure-cli-latest#az-acr-token-create twice, with the same `--name`?

**Comment by briglx** [comment]
Looks like it overwrites the previous token. Running `create` a second time created new passwords. However, running `az acr token list` showed only one token with the create date of the last one created.

**Comment by elgohr** [comment]
Awesome, will have a look next year 🎆

**Comment by elgohr** [comment]
Could you please have a look at https://github.com/elgohr/acr-login-action/releases/tag/0.1 ?
