### ISSUE TITLE
[FEATURE] Add arbitrary build options

### ISSUE THREAD

**Issue by dcyoung** [elgohr/Publish-Docker-Github-Action#57]
**Is your feature request related to a problem? Please describe.**
I'm looking to specify a parameter for the docker build option (not a build-arg) but an argument to the build command. ie: https://docs.docker.com/engine/reference/commandline/build/

Specifically I need to add `--shm-size=256m`

Perhaps this is possible but i missed it.

**Describe the solution you'd like**
A means of providing arbitrary build options.

**Describe alternatives you've considered**
Forking the repo and adding the option personally.

**Comment by elgohr** [comment]
There you go https://github.com/elgohr/Publish-Docker-Github-Action#buildoptions
https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/2.11
