### ISSUE TITLE
[FEATURE] Conditional `docker push`

### ISSUE THREAD

**Issue by Cherry** [elgohr/Publish-Docker-Github-Action#58]
We use Docker multi-stage builds heavily in our setup, and rely on these for running tests, linting, etc. and then conditionally at the end of that, push if we're in a certain branch. For example, in CircleCI we accomplish this with:

```
- run:
    name: docker build
    command: |
      docker login -u $DOCKER_USER -p $DOCKER_PASS
      docker pull base
      docker build --rm=false -t foobar .
- deploy:
    name: docker push
    command: |
      if [ "${CIRCLE_BRANCH}" == "master" ]; then
        docker push foobar
      fi
```

As far as I can tell, this isn't possible with this action, and the `push` will always occur.

**Comment by elgohr** [comment]
The action itself is a multi-staged build...
https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/Dockerfile

**Comment by Cherry** [comment]
So to confirm, there's no way to use this action to _just_ build the container, and not push?

**Comment by elgohr** [comment]
That's why the action is called **Publish**-Docker-Github-Action

**Comment by elgohr** [comment]
Please have a look at https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/2.20
