### ISSUE TITLE
could not push to git hub docker registry

### ISSUE THREAD

**Issue by gartcimore** [elgohr/Publish-Docker-Github-Action#60]
Hello,
I'm trying to push to github docker registry.
I have the following git hub action :
`name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.3
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy the Docker image to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gartcimore/jb3
        dockerfile: Dockerfile.jb3only
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tag_names: true
`

But I got the following error

Successfully built 1a47a44da186
Successfully tagged docker.pkg.github.com/gartcimore/jb3:docker-registry
The push refers to repository [docker.pkg.github.com/gartcimore/jb3]
ddb89dc1187e: Preparing
3684a97eea90: Preparing
48aa487fb4a7: Preparing
c6671cb4163d: Preparing
21663ac9e08e: Preparing
77cae8ab23bf: Preparing
77cae8ab23bf: Waiting
name unknown: docker image push is only supported with a tag of the format :owner/:repo_name/:image_name.
		Please add an image name to "gartcimore/jb3" tag. e.g. "gartcimore/jb3/<image_name>"
##[error]Docker run failed with exit code 1

It must something simple but I can not find what I am missing

**Comment by elgohr** [comment]
Please read the documentation https://github.com/elgohr/Publish-Docker-Github-Action#registry

**Comment by kepikoi** [comment]
Struggled as well on this a bit. In OPs example the image name was missing in the name argument which is required by GitHub Packages

```
  with:
    name: gartcimore/jb3
```
 should have been 
```
  with:
    name: gartcimore/jb3/his-img-name
```
