### ISSUE TITLE
[FEATURE] Authenticate using GITHUB_TOKEN

### ISSUE THREAD

**Issue by potiuk** [elgohr/Publish-Docker-Github-Action#62]
**Is your feature request related to a problem? Please describe.**
Currently in order to authenticate with Github registry I need to generate personal access token and set it as password in my project's secrets. Similarly to what is described here:
https://help.github.com/en/github/managing-packages-with-github-packages/configuring-npm-for-use-with-github-packages#authenticating-to-github-packages

However in GithubActions we have GITHUB_TOKEN set automatically which enables to authenticate using automatically generated GITHUB_TOKEN in case we are pushing to github packages registry and not to Github Packages repo:

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token

This has the added value that we can use current project as the repo to push and then this plugin would work for all Github forks automatically.

It would be great if we can have it.

**Describe the solution you'd like**
In case GITHUB_TOKEN is defined, no user and password should be needed. GITHUB_TOKEN should be used and current user/project should be used as a base for the registry to push the image to.

**Describe alternatives you've considered**
- user / passwrd authentication works with personal Github Token set as password but it requires you to add secrets to each fork separately.

**Comment by potiuk** [comment]
I am happy to add this feature BTW!

**Comment by elgohr** [comment]
Cool idea 🙂
Are you sure that the `GITHUB_TOKEN` has the needed scope to push an image to packages? 
Tried to use it in another action for creating a release/tag and this didn't work.

**Comment by elgohr** [comment]
Furthermore, how would we handle the situation where somebody would like to publish images on a different repositories packages (`GITHUB_TOKEN` is repository scoped)

**Comment by potiuk** [comment]
Well. I think it has all the reuired scope, but maybe what we need to do is just update the docs:

The scope is here https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token 

I just found an issue it was not working for some time but it has been fixed.... https://github.com/actions/starter-workflows/issues/66

However in the same issue, it seems that it's just enough to properly set the configuration:

```
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
```

And probably it will work out-of-the-box - and it should also solve the problem how to publish on a different repositories . - same way as before - using secrets.

So it looks like it's a doc-only change :)

**Comment by elgohr** [comment]
Ah, now I got you :smile: 
I would like to try this in the integration tests first.

**Comment by potiuk** [comment]
I will try it in my repo as well.

**Comment by potiuk** [comment]
BTW there is an Action that does exactly this - but only for the GithubRepo: https://github.com/matootie/github-docker

**Comment by elgohr** [comment]
There we go, looks good :smiley: 
https://github.com/elgohr/Publish-Docker-Github-Action/commit/afe350c38f2a94ea8de390ec0f8631577d21c001/checks?check_suite_id=384397532

**Comment by potiuk** [comment]
Nice! But I would love to get it to the state where everyone will get it working with their own fork without changing anything! In the integration tests you have hard-coded name of the owner/repo and if we can get it from the variables, that would be awesome.

So far I have a problem with setting OWNER in the name: field :

**Comment by potiuk** [comment]
https://github.com/potiuk/periodic-labeler/commit/50421ce2e1333b12b55bd373b476190bb23f9335/checks?check_suite_id=384403272

Shows what happens

**Comment by potiuk** [comment]
Total Bummer. Even if we make it works - it seems that you  HAVE to authenticate with Github even if you want to download public image! 

https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782/highlight/false

It makes github docker packages so useless.. .. Totally disappointed with them.

**Comment by elgohr** [comment]
Oh could have told you that.
You're welcome to jump in https://twitter.com/lagohr/status/1150115700318658560

**Comment by potiuk** [comment]
July 2019! !?!?!?!? :(. That's really, really, really bad....

**Comment by potiuk** [comment]
Jumped in!

**Comment by potiuk** [comment]
Unfortunately - it seems that the env variables from Github Actions are only available to "run" fields only (also not mentioned in the documentation) :( . So nothing easily usable for that case.

**Comment by elgohr** [comment]
Haven't tried it yet, but what about something like `name: ${{ github.repository }}` (https://github.com/elgohr/Publish-Docker-Github-Action/issues/59)?

**Comment by elgohr** [comment]
Do we want to close this? My guess is that the `name` isn't used that generic....
