### ISSUE TITLE
[FEATURE] Using this tool for GitHub Actions, {{ github.repository }} has capital letters in it, which aren't valid for Docker image names. Maybe the implicit thing should be done and the name should be lowercased?

### ISSUE THREAD

**Issue by nelsonjchen** [elgohr/Publish-Docker-Github-Action#63]
**Is your feature request related to a problem? Please describe.**
When using this tool for GitHub Packages, use of the `{{ github.repository }}` variable is tricky. For starters, image names can only be lowercase. However, `{{ github.repository }}` can have uppercase letters. 

Here's an example of a naive use of `{{ github.repository }}`. The push fails as it has uppercase letters.

https://github.com/nelsonjchen/CamelCaseGhpRepoName/runs/385360225

Repo names can have capital letters (like elgohr/Publish-Docker-Github-Action!) as well as users/organizations like my day job's. That's kind of how I discovered this annoying issue.

**Describe the solution you'd like**
Maybe just handle implicitly lowercasing the `name`? Should this be a "just do what I mean"?

I think names must be lowercase anyway as you can see from this search:

https://github.com/search?q=invalid+reference+format%3A+repository+name+must+be+lowercase&type=Code

It seems many tools enforce lowercasing.

This shouldn't cause any backwards compatibility issues if that's the case. 

**Describe alternatives you've considered**

Here we use a small bashism to just lowercase the name and set a variable that the publishing step can use. [I script kiddied this thing that's barely even a one-liner from Stackoverflow here](https://stackoverflow.com/a/2264537/286021) to set a variable that the publishing step could use. 

https://github.com/nelsonjchen/CamelCaseGhpRepoName/runs/385360230

**Comment by elgohr** [comment]
There are so many characters, that aren't valid as docker-names and docker-tags.
I would expect people to change the repository name or set it explicitly. This action isn't a linter.

**Comment by nelsonjchen** [comment]
OK, that makes sense. For now, I'll leave this issue around as documentation of a workaround to lowercase the names.
