### ISSUE TITLE
[FEATURE] Allow buildargs that call commands

### ISSUE THREAD

**Issue by eteubert** [elgohr/Publish-Docker-Github-Action#64]
**Is your feature request related to a problem? Please describe.**

I want to have access to my git commit sha in the release. I am following this short guide: https://artsy.github.io/blog/2018/09/10/Dockerhub-Stamping-Commits/

**Describe the solution you'd like**

I tried this: `buildargs: COMMIT=$(git rev-parse --short HEAD)` but it does not execute. `COMMIT` then has the value of `$(git`.

**Describe alternatives you've considered**

There needs to be any way to execute a command on the host and get the output into the container. Build Args seem the right approach to me.

**Comment by elgohr** [comment]
So why don't you use `github.sha` (https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#github-context) ?

**Comment by eteubert** [comment]
Didn't know about it :) Works, thanks!
