### ISSUE TITLE
[FEATURE] Major releases

### ISSUE THREAD

**Issue by hazcod** [elgohr/Publish-Docker-Github-Action#67]
**Is your feature request related to a problem? Please describe.**
When a specific version of a docker image is updated (e.g. 3.1.2), this should reflect in the major version tag as wel. (e.g. 3.1 or 3)

**Describe the solution you'd like**
Ability to push to the major versions. 3.1.2 would push to 3.1 and 3.
You could for example split the version string on a dot, ommit the last element & pushlish in a loop.

**Describe alternatives you've considered**
None

**Comment by elgohr** [comment]
How can this action know whether the changes made to the code had been incompatible (major) or not (minor) or bug fixes (https://semver.org/)?

**Comment by hazcod** [comment]
Sorry, indeed the second part.

**Comment by elgohr** [comment]
Great idea, how would you name such a feature? 🙂

**Comment by hazcod** [comment]
@elgohr I would say `pushUpstream`? Or `propagateUpstream`?

**Comment by elgohr** [comment]
Would this also push to latest?

**Comment by hazcod** [comment]
From a docker perspective, it does not even matter if you are using semver or not.
But it boils down to the same: when you publish changes on a minor version tag, those changes should reflect in the major version tag.
I would offer `latest` with a toggle, since it is looked down upon as a bad practice. (can introduce breaking changes)

**Comment by elgohr** [comment]
You're aware of the fact that this action is doing it the other way around?
If you're using any semver in `tags` that's your choice. Not everybody is doing that and per default this action publishes master to latest, when not using `tags`

**Comment by elgohr** [comment]
A way you could do that already would be using https://github.com/marketplace/actions/update-major-minor-semver and `tag_names`

**Comment by hazcod** [comment]
Thank you for that suggestion @elgohr , works!

**Comment by elgohr** [comment]
So we can close this?

**Comment by elgohr** [comment]
Maybe this could also be interesting here https://github.com/elgohr/Publish-Docker-Github-Action#tag_semver
