### ISSUE TITLE
[Request] Support for specified dockerfiles

### ISSUE THREAD

**Issue by jhoward321** [elgohr/Publish-Docker-Github-Action#7]
Are there plans to add support for a specified dockerfile? For example in one of my projects I have 3 dockerfiles inside of a directory. It would be great if there was an option to specify a specific dockerfile path as an optional argument. It could default to Dockerfile in the root of the repository.

**Comment by elgohr** [comment]
Thank you for the idea.
There you go https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/1.2 :)

**Comment by jhoward321** [comment]
Wow thanks for such a fast turnaround!

**Comment by jhoward321** [comment]
So I noticed one thing that could improve this. When specifying a custom dockerfile, you are supposed to use a -f option before specifying the file. In the entry point it would make it easier it always have this flag, but have the default value just set to 'Dockerfile' if none is specified. A current workaround is passing "-f path/to/CustomDockerfile"
