### ISSUE TITLE
[FEATURE] Skip build step

### ISSUE THREAD

**Issue by pixie79** [elgohr/Publish-Docker-Github-Action#72]
Is there an option to skip the build step of this action?

I like what you have done and it is very useful for publishing and setting all the tag types however, before publishing we are using https://github.com/marketplace/actions/anchore-container-scan. This requires us to build a container first. Currently as you can see we end up building twice. 

Ideally the flow should be - 

1. Build container
2. Anchore scan - if fails abort
3. Use built container tag and push

For info my current build steps are:
name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      - uses: anchore/scan-action@master
        with:
          image-reference: "localbuild/testimage:latest"
          dockerfile-path: "./Dockerfile"
          fail-build: false
          include-app-packages: true
      - name: anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: digitalpatterns/jdk/master
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          snapshot: true
          tags: "latest, ${{ github.sha }}"

Thanks

**Comment by elgohr** [comment]
You could try caching https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/README.md#cache

**Comment by pixie79** [comment]
I am not sure caching is the same ? is that not caching the parts rather than the docker image. Ideally we need to build the image every time at step 1, but then pass in an image name to the publish step so that it skips and moves straight to tagging.

That way step 1 would build fully every time.

**Comment by elgohr** [comment]
The result is the same, isn't it? 😉
So, no, there is nothing like that.

**Comment by elgohr** [comment]
You could also put the scan action after the publish and drop the build....

**Comment by pixie79** [comment]
oh so cache is docker cache - sorry penny has dropped now, so yes in theory that would work as the previous layer builds it and this just uses the cached build.

If i put the scan after the publish if the scan fails we have published a build with know vulnerabilities (yes i know the config at the moment does that whilst testing :) )

Thanks

**Comment by elgohr** [comment]
So we can close this?

**Comment by patcon** [comment]
First off, thanks for this action! Really appreciate it :)

As another use-case for being able to push without building: We build with docker-compose, since we already manage all our complex env_file stuff in there. To be able to get a cache hit, we'd have to re-implement all the same env stuff, and keep it in sync.

Having a `skip_build` arg would be really helpful. Would you be open to accepting a PR for this?
