### ISSUE TITLE
[BUG] Can't access Git LFS files in build

### ISSUE THREAD

**Issue by Adizbek** [elgohr/Publish-Docker-Github-Action#73]
[BUG] Can't access Git LFS files in dockerfile

**Comment by elgohr** [comment]
Please follow the template. Thank you

**Comment by Adizbek** [comment]
Fixed

**Comment by elgohr** [comment]
Maybe you could also take your time explaining, not only filling headlines.

**Comment by elgohr** [comment]
From the vague idea that I get from your description, this might help you https://github.com/actions/checkout/issues/66#issuecomment-553107218
