### ISSUE TITLE
Repo with multiple projects

### ISSUE THREAD

**Issue by sergeysova** [elgohr/Publish-Docker-Github-Action#74]
I have a repo with three projects.

- I want to build a new docker image of each project on each push and assign a snapshot tag as a version.
- I want to update `latest` tag for the changed project
- I want to push a new git tag for each project and push `1` `1.2` `1.2.2` tags to docker registry

For example:

#### Changes to branch
1. I push changes to `master` branch to `first-app` directory
2. Should be built and pushed docker image with next tags:
    - `docker.pkg.github.com/user/project/first-app:202003011249095b9727`
    - `docker.pkg.github.com/user/project/first-app:latest`

#### New release
1. I push git tag `first-app@1.2.3`
2. Should be built and pushed docker image with next tags:
    - `docker.pkg.github.com/user/project/first-app:1`
    - `docker.pkg.github.com/user/project/first-app:1.2`
    - `docker.pkg.github.com/user/project/first-app:1.2.3`

The same for `second-app` and `third-app`

Work directory is the root of the repo.

How can I configure it using a single Github CI file?

**Comment by elgohr** [comment]
```
If you just came here because you want to have a one-on-one configuration session, please consider contacting me directly, as my PayPal is wide open. I don't run this as a business. So all the money gained by this will go directly to https://www.welthungerhilfe.org .
```

**Comment by sergeysova** [comment]
I made https://github.com/sergeysova/docker-publish-action
