### ISSUE TITLE
[BUG]: Minor Documentation Update

### ISSUE THREAD

**Issue by scrumpi3** [elgohr/Publish-Docker-Github-Action#75]
**Describe the bug**
The two tag fields (tag_names, tag_semver) no longer work in the version 2.14. I suggest removing them from the README.

**To Reproduce**
Add a GitHub action that uses either field tag_names or tag_semver.

**Expected behavior**
I expected the release version from Github as the image tag, but instead the image digest was used.

**Additional context**
Thank you for the action.  It makes my DevOps simpler.

**Comment by elgohr** [comment]
Tests say something different.
Could you please provide your configuration and the logs?

**Comment by scrumpi3** [comment]
I added the stage below to my deployment workflow and the docker image tag that was applied to the image in docker hub was the image digest, not the release version.  I also tried `tag_names: true` and got the same result.

--begin stage definition
`  name: Publish to Registry`
`  uses: elgohr/Publish-Docker-Github-Action@2.14`
`  with:`
`     name: orgName/repoName`
`     username: ${{ secrets.DOCKER_USERNAME }}`
`     password: ${{ secrets.DOCKER_PASSWORD }}`
`     tag_semver: true`
-- end stage definition

-- begin log
Run elgohr/Publish-Docker-Github-Action@master
  with:
    name: ***/dome
    username: ***
    password: ***
    tag_semver: true
/usr/bin/docker run --name e87b52205e47b60b954257ab602c3a79d0e733_4f5ca7 --label e87b52 --workdir /github/workspace --rm -e INPUT_NAME -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_TAG_SEMVER -e INPUT_REGISTRY -e INPUT_SNAPSHOT -e INPUT_DOCKERFILE -e INPUT_WORKDIR -e INPUT_BUILDARGS -e INPUT_CACHE -e INPUT_TAG_NAMES -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/DOME/DOME":"/github/workspace" e87b52:205e47b60b954257ab602c3a79d0e733
WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
Sending build context to Docker daemon  1.053GB
Step 1/4 : FROM tomcat:9.0.10-jre10
...download updates removed
 ---> 8816b58c9e37
Successfully built 8816b58c9e37
Successfully tagged ***/dome:889c6fa1cd9082973821c01799095fb3efe1664d
The push refers to repository [docker.io/***/dome]
...packaging updates removed
ad27e9bd33a4: Pushed
889c6fa1cd9082973821c01799095fb3efe1664d: digest: sha256:3962a6424000ba96ac543895efc415e913541055d63c027dab7d9645dc4b96a0 size: 2837
Removing login credentials for https://index.docker.io/v1/
--end log

**Comment by elgohr** [comment]
And you tagged the commit?

**Comment by scrumpi3** [comment]
I was using a release tag, but I guess I'm unclear on the appropriate process. The solution I have is working for me now.
