### ISSUE TITLE
[Request] Support for image name

### ISSUE THREAD

**Issue by jhoward321** [elgohr/Publish-Docker-Github-Action#8]
Currently the action uses the repository for the image name. I love the tagging features, but for my use case I have 2 images associated with my repository. Could we specify a custom image name so I can differentiate between these 2 images?

**Comment by elgohr** [comment]
Is there a reason that you want them to be hop:tag1 and hop:tag2 instead of hop1:tag and hop2:tag ?
I would like to keep this resource as easy as possible...

**Comment by jhoward321** [comment]
I can do it that way, I'm fine with that tradeoff.
