### ISSUE TITLE
[BUG] The operation was canceled.

### ISSUE THREAD

**Issue by Borda** [elgohr/Publish-Docker-Github-Action#83]
**Describe the bug**
We have a docker image which runs fine locally, but on GH actions fail without any extra error message, just `##[error]The operation was canceled.` and it seems that the failing ins random build process...

**To Reproduce**
https://github.com/Borda/pytorch-lightning/runs/663028682?check_suite_focus=true

**Expected behavior**
Finish the cocker build...

**Additional context**

**Comment by elgohr** [comment]
One of your matrix builds failed, so all abort (https://github.community/t5/GitHub-Actions/Build-got-was-canceled-unexpectedly/td-p/30360)

**Comment by Borda** [comment]
Ok, but why it failed?
Never mind, better use original...
https://www.docker.com/blog/first-docker-github-action-is-here

**Comment by elgohr** [comment]
Sorry, but don't blame others for your failures.

```
ERROR: Could not find a version that satisfies the requirement torch==1.3 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0) 

ERROR: No matching distribution found for torch==1.3
```
Is the cause, which is far away from this action.

**Comment by Borda** [comment]
My bad with canceling... But how shall I explain that the same Dockerfile runs locally fine also with the other action but here fails?

**Comment by elgohr** [comment]
Because your local environment is not (3.8, 1.3) ?
I guess this is Python 3.8 with version 1.3 of pytorch-light

**Comment by Borda** [comment]
but the python versions, as well as os version in running machine and docker being built, shall be strictly separated co does not matter on the local configuration

**Comment by elgohr** [comment]
Looks like it does.
