### ISSUE TITLE
[BUG] "tags" is missing in action.yml 

### ISSUE THREAD

**Issue by litetex** [elgohr/Publish-Docker-Github-Action#84]
[action.yml](https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/action.yml) is missing "tags", like described in [Readme.md](https://github.com/elgohr/Publish-Docker-Github-Action#tags-1)

Running it with the "tags" option works, but gives you a warning:
![grafik](https://user-images.githubusercontent.com/40789489/82126612-1889a900-97ae-11ea-8652-a52ad42aadfc.png)
```
##[warning]Unexpected input 'tags', valid inputs are ['name', 'username', 'password', 'registry', 'snapshot', 'dockerfile', 'workdir', 'buildargs', 'cache', 'tag_names', 'tag_semver']
```

**Comment by elgohr** [comment]
Totally oversaw that. Thank you for the issue!
Fixed in https://github.com/elgohr/Publish-Docker-Github-Action/releases/tag/2.15

**Comment by litetex** [comment]
@elgohr 
At first: Thanks for the quick response and fix 👍 

However I think you mixed ``tags`` and ``tag_names`` in the doc: https://github.com/elgohr/Publish-Docker-Github-Action/commit/fbbcb175925792809802bcb7b86408c90a7159a1

**Comment by elgohr** [comment]
🤦‍♂️ thank you
