### ISSUE TITLE
[FEATURE] Push - dont build

### ISSUE THREAD

**Issue by pixie79** [elgohr/Publish-Docker-Github-Action#88]
In a multi step github action, the last step of our build is to push to github packages and docker hub. However, the image is built in previous steps then tested and scanned for security issues.
As such I do not need this action to rebuild the image but would like to use it to take a local image that has been built in the previous docker step and then tag it before pushing.

As you will see here, we build the image in the first step, that image is then used by Anchore to be scanned, after which the same image should be published. Instead even though cache is enabled it rebuilds.

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'repo/image/name'
      IMAGE_DOCKER_HUB: 'repo/imagename'
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE }}:latest
      - uses: anchore/scan-action@v1.0.4
        with:
          image-reference: "${{ env.IMAGE }}:latest"
          dockerfile-path: "./Dockerfile"
          fail-build: false
          include-app-packages: true
      - name: anchore inline scan JSON results
        run: cat ./anchore-reports/vulnerabilities.json;
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.IMAGE_DOCKER_HUB }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          snapshot: true
          tags: "latest"

**Comment by elgohr** [comment]
Hi, I guess you want to have a look at 
https://github.com/elgohr/Publish-Docker-Github-Action/issues/58#issuecomment-567639788
and
https://github.com/elgohr/Publish-Docker-Github-Action/issues/87

**Comment by pixie79** [comment]
No, neither of those two tickets are similar.

I do want to push using this action but i do not want to build. I already have an image built by a previous step that just needs to be tagged and then pushed. This is not the same as the multistage dockerfile issue either

**Comment by elgohr** [comment]
Ah, got it :)
I'm a little concerned about separating build and push as this adds another interface for input to the action. In addition the tagging would have to happen via `docker tag`, not via `docker build`.
Nevertheless I'm open for PRs :)

**Comment by patcon** [comment]
Came here looking for the same thing. Just realized that setting `buildoptions: "--help"` might work as a no-op, since it exits cleanly ;)
