### ISSUE TITLE
Enabling squash

### ISSUE THREAD

**Issue by Accipiter7** [elgohr/Publish-Docker-Github-Action#92]
I  wonder how can i build with experimental --squash.

**Comment by Accipiter7** [comment]
Passing --squash simply won't work

**Comment by elgohr** [comment]
I guess GitHub actions would have to enable experimental features on the workers (https://github.com/docker/docker-ce/blob/master/components/cli/experimental/README.md) or you could run an own one.

**Comment by Accipiter7** [comment]
can you add support for it in your docker.

**Comment by Accipiter7** [comment]
sudo echo "{ 
    "experimental": true 
} 
" >> /etc/docker/daemon.json 

sudo systemctl restart docker.service


Even tried this got permission denied

**Comment by Accipiter7** [comment]
Issue got solved here:

https://github.com/actions/runner/issues/533
