### ISSUE TITLE
[FEATURE] Question - How to use the output in another github step within the same action

### ISSUE THREAD

**Issue by Shaun-Harrison** [elgohr/Publish-Docker-Github-Action#99]
Sorry if this is really obvious, I've looked through existing issues but can't find what I'm after

Basically after the image has been pushed to the registry, I want to update a dockerfile in another repository with the new tag/hash - I believe its the digest is what I'm after from the output section, but how do I actually get the output to use it in the next step ?

**Comment by elgohr** [comment]
Hey, please have a look at https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context

**Comment by Shaun-Harrison** [comment]
Ah that's exactly what I'm after, thank you!
